name:                AdventOfCode
version:             0.1.0.0
github:              "githubuser/AdventOfCode"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- hashable
- heap
- megaparsec
- mtl
- split
- unordered-containers
- tasty
- tasty-hunit
- text
- transformers

library:
  source-dirs: src
  dependencies:
    - extra
    - monad-logger
    - search-algorithms
  exposed-modules:
    [ Day1
    , Day2
    , Day3
    , Day4
    , Day5
    , Day6
    , Day7
    , Day8
    , Day9
    , Day10
    , Day11
    , Day12
    , Day13
    , Day14
    , Day15
    , Day16
    , Day17
    , Day18
    , Day19
    , Day20
    , Day21
    , Day22
    , Day23
    # , Day24
    # , Day25
    ]
  other-modules:
    [ Utils
    ]

tests:
  test-2022:
    main: TestAoC2022.hs
    other-modules: []
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode

  aoc-utils-test:
    main: AocUtilsTests.hs
    other-modules: []
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AdventOfCode
      - monad-logger
